version: "3.8"

services:
  postgres:
    container_name: postgres_test_migrate
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root