version: "3.8"

services:
  postgres:
    container_name: postgres_test_migrate
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    ports:
      - 5065:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@rg.ru
      PGADMIN_DEFAULT_PASSWORD: 159753